specVersion: 0.0.6
schema:
  file: ./schema.graphql
{{#graftEnabled}}
description: ...
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{/graftEnabled}}
{{#isMainnet}}
dataSources:
{{#tokens}}
  - kind: ethereum/contract
    name: {{dataSourceName}}
    network: {{network}}
    source:
      address: '{{address}}'
      abi: Token
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - Transfer
      abis:
        - name: Token
          file: ./abis/Token.json
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/Pool.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Aave Contracts
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/hop-protocol/src/mainnet/bridge.ts
{{/tokens}}
{{#bridges}}
  - kind: ethereum/contract
    name: {{dataSourceName}}
    network: {{network}}
    source:
      address: '{{address}}'
      abi: L1_Bridge
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - BonderAdded
        - BonderRemoved
        - ChallengeResolved
        - MultipleWithdrawalsSettled
        - Stake
        - TransferBondChallenged
        - TransferRootBonded
        - TransferRootConfirmed
        - TransferRootSet
        - TransferSentToL2
        - Unstake
        - WithdrawalBondSettled
        - WithdrawalBonded
        - Withdrew
      abis:
        - name: L1_Bridge
          file: ./abis/L1_Bridge.json
      eventHandlers:
        - event: BonderAdded(indexed address)
          handler: handleBonderAdded
        - event: BonderRemoved(indexed address)
          handler: handleBonderRemoved
        - event: ChallengeResolved(indexed bytes32,indexed bytes32,uint256)
          handler: handleChallengeResolved
        - event: MultipleWithdrawalsSettled(indexed address,indexed bytes32,uint256)
          handler: handleMultipleWithdrawalsSettled
        - event: Stake(indexed address,uint256)
          handler: handleStake
        - event: TransferBondChallenged(indexed bytes32,indexed bytes32,uint256)
          handler: handleTransferBondChallenged
        - event: TransferRootBonded(indexed bytes32,uint256)
          handler: handleTransferRootBonded
        - event: TransferRootConfirmed(indexed uint256,indexed uint256,indexed bytes32,uint256)
          handler: handleTransferRootConfirmed
        - event: TransferRootSet(indexed bytes32,uint256)
          handler: handleTransferRootSet
        - event: TransferSentToL2(indexed uint256,indexed address,uint256,uint256,uint256,indexed address,uint256)
          handler: handleTransferSentToL2
        - event: Unstake(indexed address,uint256)
          handler: handleUnstake
        - event: WithdrawalBondSettled(indexed address,indexed bytes32,indexed bytes32)
          handler: handleWithdrawalBondSettled
        - event: WithdrawalBonded(indexed bytes32,uint256)
          handler: handleWithdrawalBonded
        - event: Withdrew(indexed bytes32,indexed address,uint256,bytes32)
          handler: handleWithdrew
      file: ./protocols/hop-protocol/src/mainnet/bridge.ts
{{/bridges}}
{{/isMainnet}}

{{^isMainnet}}
dataSources:
{{#tokens}}
  - kind: ethereum/contract
    name: {{dataSourceName}}
    network: {{network}}
    source:
      address: '{{address}}'
      abi: Token
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - Transfer
      abis:
        - name: Token
          file: ./abis/Token.json
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Aave Contracts
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ./protocols/hop-protocol/src/L2/token.ts
{{/tokens}}
{{#amms}}
  - kind: ethereum/contract
    name: {{dataSourceName}}
    network: {{network}}
    source:
      address: '{{address}}'
      abi: L2_Amm
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - TokenSwap
        - AddLiquidity
        - RemoveLiquidity
        - RemoveLiquidityOne
        - RemoveLiquidityImbalance
      abis:
        - name: L2_Amm
          file: ./abis/L2_Amm.json
      eventHandlers:
        - event: TokenSwap(indexed address,uint256,uint256,uint128,uint128)
          handler: handleTokenSwap
        - event: AddLiquidity(indexed address,uint256[],uint256[],uint256,uint256)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(indexed address,uint256[],uint256)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOne(indexed address,uint256,uint256,uint256,uint256)
          handler: handleRemoveLiquidityOne
        - event: RemoveLiquidityImbalance(indexed address,uint256[],uint256[],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
      file: ./protocols/hop-protocol/src/L2/amm.ts
{{/amms}}
{{#bridges}}
  - kind: ethereum/contract
    name: {{dataSourceName}}
    network: {{network}}
    source:
      address: '{{address}}'
      abi: L2_Bridge
      startBlock: {{startBlock}}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.5
      language: wasm/assemblyscript
      entities:
        - BonderAdded
        - BonderRemoved
        - MultipleWithdrawalsSettled
        - Stake
        - TransferFromL1Completed
        - TransferRootSet
        - TransferSent
        - TransfersCommitted
        - Unstake
        - WithdrawalBondSettled
        - WithdrawalBonded
        - Withdrew
      abis:
        - name: L2_Bridge
          file: ./abis/L2_Bridge.json
      eventHandlers:
        - event: BonderAdded(indexed address)
          handler: handleBonderAdded
        - event: BonderRemoved(indexed address)
          handler: handleBonderRemoved
        - event: MultipleWithdrawalsSettled(indexed address,indexed bytes32,uint256)
          handler: handleMultipleWithdrawalsSettled
        - event: Stake(indexed address,uint256)
          handler: handleStake
        - event: TransferFromL1Completed(indexed address,uint256,uint256,uint256,indexed address,uint256)
          handler: handleTransferFromL1Completed
        - event: TransferRootSet(indexed bytes32,uint256)
          handler: handleTransferRootSet
        - event: TransferSent(indexed bytes32,indexed uint256,indexed address,uint256,bytes32,uint256,uint256,uint256,uint256)
          handler: handleTransferSent
        - event: TransfersCommitted(indexed uint256,indexed bytes32,uint256,uint256)
          handler: handleTransfersCommitted
        - event: Unstake(indexed address,uint256)
          handler: handleUnstake
        - event: WithdrawalBondSettled(indexed address,indexed bytes32,indexed bytes32)
          handler: handleWithdrawalBondSettled
        - event: WithdrawalBonded(indexed bytes32,uint256)
          handler: handleWithdrawalBonded
        - event: Withdrew(indexed bytes32,indexed address,uint256,bytes32)
          handler: handleWithdrew
      file: ./protocols/hop-protocol/src/L2/bridge.ts
{{/bridges}}
{{/isMainnet}}
